---
- hosts: fabric
  become: yes
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: sudo apt-get -y install python 
#    when: ansible_os_family == "Debian"

  handlers:
    - name: ubuntu restart
      service: name=apache2 state=started enabled=yes
